

services:
  dogecoin-node:
    image: flarefoundation/dogecoin:1.14.7
    container_name: node-testnet-doge
    restart: unless-stopped
    ports:
      - 44555:44555
      - 44556:44556
    volumes:
      - dogecoin-testnet-data:/opt/dogecoin/.dogecoin/db
      - ./dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf


volumes:
  dogecoin-testnet-data:
