

services:
  dogecoin-node:
    image: flarefoundation/dogecoin:1.14.6
    container_name: node-mainnet-doge
    restart: unless-stopped
    ports:
      - 22555:22555
      - 22556:22556
    volumes:
      - dogecoin-mainnet-data:/opt/dogecoin/.dogecoin/db
      - ./dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf
    networks:
      - attestation_suite_network

volumes:
  dogecoin-mainnet-data:

networks:
  attestation_suite_network:
    external: true
