#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER $READER_USER WITH PASSWORD '$READER_PASSWORD';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $READER_USER;
GRANT USAGE ON SCHEMA public TO $READER_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READER_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $READER_USER;
EOSQL

