

services:
  verification-server:
    image: flarefoundation/attestation-client
    volumes:
      - ../credentials.prepared/doge-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-doge-verification-server
    command: verification-server
    restart: unless-stopped
    environment:
      VERIFIER_TYPE: doge
      APP_BASE_PATH: /verifier/doge
      EXTERNAL: django
      TESTNET: ${TESTNET}
    #depends_on:
    #  - database
    ports:
      - 9504:9500
    networks:
      - attestation_suite_network

  spammer:
    image: flarefoundation/attestation-client
    profiles: ["spammer"]
    volumes:
      - ../credentials.prepared/doge-indexer-verifier:/app/attestation-suite-config
    container_name: indexer-doge-spammer
    command: spammer DOGE 10000
    restart: unless-stopped
    environment:
      EXTERNAL: django
      TESTNET: ${TESTNET}
    networks:
      - attestation_suite_network


  postgresdb:
    container_name: indexer-doge-postgresdb
    image: postgres:16
    env_file:
      - doge-indexer.env
    ports:
      - 25432:5432
    restart: unless-stopped
    volumes:
      - doge-indexer-postgresdb:/var/lib/postgresql/data
    networks:
      - attestation_suite_network

  indexer-server:
    container_name: indexer-doge-server
    user: 10008:10008
    image: flarefoundation/doge-indexer
    environment:
      DB_PORT: 5432
      DB_HOST: postgresdb
    env_file:
      - doge-indexer.env
    ports:
      - 8400:8400
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - doge-indexer-static:/appdata/static
    networks:
      - attestation_suite_network

  indexer-indexer:
    container_name: indexer-doge-index-blocks
    user: 10008:10008
    image: flarefoundation/doge-indexer
    command: /app/docker/remote/entrypoint-index.sh
    environment:
      DB_PORT: 5432
      DB_HOST: postgresdb
    env_file:
      - doge-indexer.env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - doge-indexer-static:/appdata/static
    networks:
      - attestation_suite_network

  indexer-prune:
    container_name: indexer-doge-prune-blocks
    user: 10008:10008
    image: flarefoundation/doge-indexer
    command: /app/docker/remote/entrypoint-prune.sh
    environment:
      DB_PORT: 5432
      DB_HOST: postgresdb
    env_file:
      - doge-indexer.env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - doge-indexer-static:/appdata/static
    networks:
      - attestation_suite_network

volumes:
  doge-indexer-static:
  doge-indexer-postgresdb:

networks:
  attestation_suite_network:
    external: true
